import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, Info } from 'lucide-react';
import { UserRole } from '@/context/AppContext';

interface InstructionGuideProps {
  role: UserRole;
}

const instructions: Record<UserRole, { title: string; description: string }> = {
  requester: {
    title: 'Head of Department',
    description:
      'Create new procurement requests and generate AI-powered memos. Track the status of your requests through the approval workflow.',
  },
  procurement: {
    title: 'Procurement Officer',
    description:
      'Review incoming requests and verify if the items are actually needed by the department. Approve to send to Audit or Reject with a reason.',
  },
  audit: {
    title: 'Internal Audit',
    description:
      'Review compliance scores generated by AI analysis. Verify budget codes and vendor status. Flag any concerns or approve to proceed to Finance.',
  },
  finance: {
    title: 'Finance Approver',
    description:
      'Check price anomalies using the detection tool before approval. Upload payment receipts to complete transactions.',
  },
};

export function InstructionGuide({ role }: InstructionGuideProps) {
  const [dismissed, setDismissed] = useState(false);
  const instruction = instructions[role];

  if (dismissed) return null;

  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0, y: -10 }}
        animate={{ opacity: 1, y: 0 }}
        exit={{ opacity: 0, y: -10 }}
        className="bg-secondary/50 border border-border rounded-lg p-4 mb-6"
      >
        <div className="flex items-start gap-3">
          <Info className="h-5 w-5 text-muted-foreground mt-0.5 flex-shrink-0" />
          <div className="flex-1">
            <h3 className="font-body font-medium text-foreground text-sm mb-1">
              {instruction.title} Guide
            </h3>
            <p className="font-body text-sm text-muted-foreground">
              {instruction.description}
            </p>
          </div>
          <button
            onClick={() => setDismissed(true)}
            className="text-muted-foreground hover:text-foreground transition-colors"
          >
            <X className="h-4 w-4" />
          </button>
        </div>
      </motion.div>
    </AnimatePresence>
  );
}
